#!/usr/bin/env python3
"""
AI日报 v1.3 - 例行任务邮件发送脚本
使用BCC发送，包含lu.xiao@decathlon.com
"""

import smtplib
import ssl
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
SENDER_EMAIL = 'lunchwu@gmail.com'
SENDER_PASSWORD = 'bize wlmw kupz jnoc'

# 主收件人（显示在To字段）
RECIPIENT_EMAIL = 'lunchwu@gmail.com'

# BCC列表（隐藏收件人）
BCC_EMAILS = [
    'jerry.wu1@decathlon.com',
    'leanna.li@decathlon.com',
    'tia.song@decathlon.com',
    'lu.xiao@decathlon.com',  # 新增
]

def send_v13_daily_report():
    """发送AI日报 v1.3 例行任务"""
    
    report_date = '2026年3月3日'
    report_url = 'https://6085deaf.ai-daily-report-v1-3.pages.dev'
    
    # 中文摘要 - Top 3
    summary_cn = '''<p><strong>1. OpenAI完成1100亿美元史诗级融资</strong><br/>OpenAI于3月2日宣布完成史上最大规模融资，金额高达1100亿美元，投后估值飙升至7300亿美元。</p>
<p><strong>2. 银河通用再融25亿元</strong><br/>3月2日，银河通用机器人宣布完成25亿元新一轮融资，估值超30亿美元。</p>
<p><strong>3. 阿里智能客服双11处理90%咨询</strong><br/>阿里巴巴基于通义千问大模型打造的智能客服系统，在2025年双11期间成功处理了90%以上的消费者咨询。</p>'''
    
    # 英文摘要 - Top 3
    summary_en = '''<p><strong>1. OpenAI Closes $110B Funding Round</strong><br/>On March 2, OpenAI announced the largest private funding round in history, raising $110 billion.</p>
<p><strong>2. Galbot Raises $362M</strong><br/>On March 2, Galbot announced a new funding round of 2.5 billion yuan.</p>
<p><strong>3. Alibaba Smart Customer Service Handled 90% of Inquiries</strong><br/>Alibaba\'s system successfully handled over 90% of consumer inquiries during Double 11 2025.</p>'''
    
    subject = f'📰 AI Daily Report v1.3 | {report_date}'
    
    body = f'''<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;line-height:1.6;color:#333;max-width:600px;margin:0 auto;padding:20px}}
h2{{color:#667eea;border-bottom:2px solid #667eea;padding-bottom:10px}}
h3{{color:#333;margin-top:25px}}
.link-box{{background:linear-gradient(135deg,#667eea,#764ba2);padding:15px;border-radius:10px;margin:20px 0;text-align:center}}
.link-box a{{color:white;text-decoration:none;font-weight:bold;font-size:1.1rem}}
.summary{{background:#f8f9fa;padding:15px;border-radius:8px;margin:15px 0;border-left:4px solid #667eea}}
.summary p{{margin:12px 0;line-height:1.8}}
.footer{{margin-top:30px;padding-top:20px;border-top:1px solid #ddd;color:#666;font-size:0.9rem;text-align:center}}
</style></head>
<body>
<h2>📰 AI Daily Report v1.3 | {report_date}</h2>
<div class="link-box"><a href="{report_url}">📎 点击阅读完整报告 / View Full Report</a></div>
<h3>📝 中文摘要 / Chinese Summary</h3><div class="summary">{summary_cn}</div>
<h3>📝 English Summary</h3><div class="summary">{summary_en}</div>
<div class="footer"><p>此邮件由 AI 助手自动生成 | Auto-generated by AI Assistant</p>
<p>报告时间：{report_date} 07:30 (Asia/Shanghai)</p></div>
</body></html>'''
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL  # 只显示主收件人
    # 不设置CC，所有其他收件人使用BCC
    
    msg.attach(MIMEText(body, 'html', 'utf-8'))
    
    # 发送邮件（To + BCC）
    all_recipients = [RECIPIENT_EMAIL] + BCC_EMAILS
    
    for i in range(5):
        try:
            context = ssl.create_default_context()
            with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=15) as server:
                server.starttls(context=context)
                server.login(SENDER_EMAIL, SENDER_PASSWORD)
                server.sendmail(SENDER_EMAIL, all_recipients, msg.as_string())
            print(f'✅ v1.3例行任务完成')
            print(f'   To: {RECIPIENT_EMAIL}')
            print(f'   BCC: {len(BCC_EMAILS)}人')
            return True
        except Exception as e:
            print(f'尝试{i+1}失败: {e}')
            time.sleep(3)
    
    return False

if __name__ == '__main__':
    send_v13_daily_report()
